services:
  react-frontend:
    image: gym-react-frontend-local
    command: ["start"]
    ports:
      - "8080:3000"
    networks:
      - gym-net
    volumes:
      - ./:/app
    depends_on:
      - backend-api
    build: .
  backend-api:
    image: eahlberg12/gym-node-backend
    command: ["api-only"]
    ports:
      - "8081:3000"
    networks:
      - gym-net
    volumes:
      - ./node-backend-config_local:/var/www/config

networks:
  gym-net:
    driver: bridge
